<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b9d58ced-1dc8-4a1b-989e-cd8265fab0f5</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_bike_light</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#remove-sauce-labs-bike-light</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'remove-sauce-labs-bike-light') and equals(@name,'remove-sauce-labs-bike-light') and equals(@class,'btn btn_secondary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary btn_small btn_inventory</value>
        <webElementGuid>60d30c4e-14c4-4c68-9b36-7cc04c9018eb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>remove-sauce-labs-bike-light</value>
        <webElementGuid>c0bba1a8-4f9f-4ac7-84dd-c099be979b40</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-bike-light</value>
        <webElementGuid>98ea44a6-5dbe-453f-abcb-4246f205df71</webElementGuid>
    </webElementProperties>
</WebElementEntity>