<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b0c5452a-4f5c-4c12-84a1-82d14d19c60c</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_bike_light</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#remove-sauce-labs-bike-light</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'remove-sauce-labs-bike-light') and equals(@name,'remove-sauce-labs-bike-light') and equals(@class,'btn btn_secondary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary btn_small btn_inventory</value>
        <webElementGuid>c86dd1e4-4078-4c88-99e2-f89a59af19b9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>remove-sauce-labs-bike-light</value>
        <webElementGuid>80406287-dba3-4f35-b966-692bad5ba19f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-bike-light</value>
        <webElementGuid>08912b1d-3142-4e84-bbc9-7cc697cd9bad</webElementGuid>
    </webElementProperties>
</WebElementEntity>