<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>06b17a11-061b-4a2c-95fe-b71977fa184a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_item_4_title_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#item_4_title_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'item_4_title_link') and equals(@text,'Sauce Labs Backpack')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#item_4_title_link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>item_4_title_link</value>
        <webElementGuid>c4251595-6f9f-4802-929c-2c32afa3d057</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sauce Labs Backpack</value>
        <webElementGuid>c4251595-6f9f-4802-929c-2c32afa3d057</webElementGuid>
    </webElementProperties>
</WebElementEntity>