<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74b98c23-5093-4041-b463-81d8755716ed</elementGuidId>
    <imagePath></imagePath>
    <name>button_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#checkout</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'checkout') and equals(@name,'checkout') and equals(@class,'btn btn_action btn_medium checkout_button ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium checkout_button </value>
        <webElementGuid>3e7c2936-f630-4d59-8244-c97e4741b0ec</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>1c44e2ce-ccb7-43c4-a284-ff81e4cf8b37</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>92fefc32-993b-44d2-b621-00643f411b7e</webElementGuid>
    </webElementProperties>
</WebElementEntity>