<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6f3f4ed7-83ee-4b74-9b58-55edbd2208e4</elementGuidId>
    <imagePath></imagePath>
    <name>input_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#last-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'last-name') and equals(@name,'lastName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>6535b346-a278-463b-9964-17a92fd12e95</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>last-name</value>
        <webElementGuid>10dd7480-d3f6-4ced-a441-daa1a08e90cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>lastName</value>
        <webElementGuid>21a4b458-608c-4309-9764-c2d41d51602d</webElementGuid>
    </webElementProperties>
</WebElementEntity>