<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>397a59e1-5134-4bca-ab8e-741ebea724c1</elementGuidId>
    <imagePath></imagePath>
    <name>input_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#last-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'last-name') and equals(@name,'lastName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>a997c569-3a66-417c-b539-934b2b30402b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>last-name</value>
        <webElementGuid>61d369e0-ddbe-4f97-8326-2d613fb4fdb9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>lastName</value>
        <webElementGuid>a40353c3-1a90-4beb-9562-f7deeff03880</webElementGuid>
    </webElementProperties>
</WebElementEntity>