<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a6b5f134-52c5-4893-8297-ef868a584269</elementGuidId>
    <imagePath></imagePath>
    <name>input_first_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#first-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'first-name') and equals(@name,'firstName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>f5412816-d56c-41a1-bc2c-42eeb8e4ca7d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>first-name</value>
        <webElementGuid>6bcb906a-5496-498b-a641-519acb8677d0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>firstName</value>
        <webElementGuid>ed25d456-7e8b-4d4e-a464-e31b5353d4ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>