<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a3b4f37e-6005-419d-aee0-2a1668253b1a</elementGuidId>
    <imagePath></imagePath>
    <name>input_postal_code</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#postal-code</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'postal-code') and equals(@name,'postalCode') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>d361128a-f979-46b4-aed8-7547a2067cec</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>postal-code</value>
        <webElementGuid>47903454-a9f4-4dd1-9f72-c6d1b04da099</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>postalCode</value>
        <webElementGuid>27860dc5-dfe0-41da-9072-abea9edff162</webElementGuid>
    </webElementProperties>
</WebElementEntity>